// DO NOT EDIT. This file is generated by citric.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/+layout.tsx";
import * as $1 from "./routes/+page.tsx";
import * as $2 from "./routes/[name]/+page.tsx";
import * as $3 from "./routes/api/joke/+page.ts";
import * as $$0 from "./lib/Counter.island.tsx";

const manifest = {
  routes: {
    "/+layout": $0,
    "/+page": $1,
    "/[name]/+page": $2,
    "/api/joke/+page": $3,
  },
  islands: {
    "./lib/Counter.island.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
